# Generated by Django 3.2.2 on 2021-05-16 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forums', '0003_discussion_author'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='discussion',
            name='author',
        ),
    ]
