# Generated by Django 3.2.2 on 2021-05-16 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='surname',
            field=models.TextField(default='ФИО', max_length=150),
        ),
    ]
