# Generated by Django 3.2.2 on 2021-05-16 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_surname'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='name',
            field=models.TextField(default='Имя', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.TextField(default='Фамилия', max_length=150),
        ),
    ]
