# Generated by Django 3.2.2 on 2021-05-16 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_auto_20210516_0956'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='name',
            field=models.TextField(blank=True, default='Имя', max_length=150),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='surname',
            field=models.TextField(blank=True, default='Фамилия', max_length=150),
        ),
    ]
